### ISSUE TITLE
Error: endorsement failure during invoke. 

### ISSUE THREAD

**Issue by softreform** [mallikprojects/hyperledger-k8#1]
peer chaincode invoke -C common -n very-simple -c '{"Function":"IndividualContract:createUser","Args":["IndividualContract:createUser","abc"]}'

I gave ERROR
Error: endorsement failure during invoke. response: status:500 message:"transaction returned with failure: Received unknown function IndividualContract:createUser invocation"

Who can help with it ?

**Comment by mallikprojects** [comment]
Its more related to chaincode error. I guess either the functional is not available or you are using old version of chaincode. If function exists, may be either delete old chain code or rename and try out

**Comment by softreform** [comment]
I need help with instantiate & invoke ( we are using fabric-contract-api NOT fabric-shim )
1. I generated TypeScript simple contract using IBM Blockchain Platform for VScode
2. Chaincode worked and tested all functions.
3. I commented on all "invoke" function in "chain-flow" templates.

Could you please add CLI to this branch?

Result of "chain-flow" is ERROR :
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg transaction returned with failure: Error: You've asked to invoke a function that does not exist:

I attached the generated TypeScript contract.
[mytiche.zip](https://github.com/mallikprojects/hyperledger-k8/files/3842500/mytiche.zip)

![image](https://user-images.githubusercontent.com/54245293/68786700-e3f33400-0648-11ea-9758-0c236e01ad6b.png)

Could you please check does this scripts work with fabric-contract-api chaincodes ( node.js language TypeScript) 
You examples work good ( fabric-shim examples )

**Comment by softreform** [comment]
Hi everyone. This is amazing - its work. Very thanks for help !!!
Chaincodes based on fabric-contract-api need to be invoked in chaincode-flow with next --ctor :
Example :
--ctor '{"Function":"IndividualContract:createUser","Args":["invokeFirstUser"]}'
![image](https://user-images.githubusercontent.com/54245293/69009542-c2eb5580-095e-11ea-977a-fdd87cb86b23.png)

![image](https://user-images.githubusercontent.com/54245293/69009534-a8b17780-095e-11ea-8321-aa306cf05c04.png)
