### ISSUE TITLE
Upgrade chaincode ERROR

### ISSUE THREAD

**Issue by softreform** [mallikprojects/hyperledger-k8#2]
Hi.
There is a render error when I trying to update chaincode.
Could you please fix that ?

![image](https://user-images.githubusercontent.com/54245293/69232197-3d9cb680-0b93-11ea-9ee4-859f4f8c47f7.png)

**Comment by mallikprojects** [comment]
I guess it is not picking vault.yaml. try this
helm upgrade hlf-init-kube ./hlf-init-kube -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml  -f samples/simple/vault.yaml
